import { useEffect, useRef } from "react";
import { CheckCircle, AlertCircle, Info, AlertTriangle, X } from "lucide-react";
import gsap from "gsap";

/**
 * Bond UI — Toast
 *
 * Render <ToastContainer> once at app root (inside ToastContext).
 * Use the useToast() hook to trigger toasts.
 *
 * Toast props:
 *  id       string  — unique id (auto-generated by context)
 *  type     "success" | "error" | "warning" | "info"
 *  title    string
 *  message  string  (optional detail)
 *  duration number  ms before auto-dismiss (default 4000, 0 = sticky)
 *  onClose  fn
 */

const configs = {
  success: {
    icon: CheckCircle,
    bar: "bg-[#3E7A58]",
    iconClass: "text-[#3E7A58]",
    bg: "bg-white",
    title: "text-[#1A2820]",
  },
  error: {
    icon: AlertCircle,
    bar: "bg-[#D4735A]",
    iconClass: "text-[#D4735A]",
    bg: "bg-white",
    title: "text-[#1A2820]",
  },
  warning: {
    icon: AlertTriangle,
    bar: "bg-[#C8883A]",
    iconClass: "text-[#C8883A]",
    bg: "bg-white",
    title: "text-[#1A2820]",
  },
  info: {
    icon: Info,
    bar: "bg-[#2A5940]",
    iconClass: "text-[#2A5940]",
    bg: "bg-white",
    title: "text-[#1A2820]",
  },
};

export function Toast({ id, type = "info", title, message, duration = 4000, onClose }) {
  const toastRef = useRef(null);
  const progressRef = useRef(null);
  const cfg = configs[type];
  const Icon = cfg.icon;

  useEffect(() => {
    const el = toastRef.current;

    /* Slide in */
    gsap.fromTo(
      el,
      { x: 60, opacity: 0 },
      { x: 0, opacity: 1, duration: 0.4, ease: "power3.out" }
    );

    /* Progress bar drain */
    if (duration > 0 && progressRef.current) {
      gsap.fromTo(
        progressRef.current,
        { scaleX: 1 },
        {
          scaleX: 0,
          duration: duration / 1000,
          ease: "none",
          transformOrigin: "left",
          onComplete: () => dismiss(),
        }
      );
    }
  }, []);

  const dismiss = () => {
    gsap.to(toastRef.current, {
      x: 60,
      opacity: 0,
      duration: 0.3,
      ease: "power2.in",
      onComplete: () => onClose?.(id),
    });
  };

  return (
    <div
      ref={toastRef}
      className={[
        "relative flex items-start gap-3 w-80 rounded-xl overflow-hidden",
        "border border-[rgba(28,61,46,0.12)] shadow-lg",
        "px-4 py-3.5",
        cfg.bg,
      ].join(" ")}
    >
      {/* left accent bar */}
      <div className={`absolute left-0 inset-y-0 w-[3px] ${cfg.bar}`} />

      <Icon size={17} strokeWidth={2} className={`shrink-0 mt-0.5 ${cfg.iconClass}`} />

      <div className="flex-1 min-w-0">
        {title && (
          <p className={`text-sm font-medium leading-snug ${cfg.title}`}>{title}</p>
        )}
        {message && (
          <p className="text-xs text-[#7A9285] leading-relaxed mt-0.5">{message}</p>
        )}
      </div>

      <button
        onClick={dismiss}
        className="shrink-0 p-0.5 rounded-md text-[#7A9285] hover:text-[#1C3D2E] hover:bg-[#F2EDE4] transition-colors"
      >
        <X size={13} strokeWidth={2} />
      </button>

      {/* progress bar */}
      {duration > 0 && (
        <div
          ref={progressRef}
          className={`absolute bottom-0 left-0 h-[2px] w-full origin-left ${cfg.bar} opacity-40`}
        />
      )}
    </div>
  );
}

/**
 * ToastContainer — place once at app root.
 * Receives `toasts` array from ToastContext.
 *
 * <ToastContainer toasts={toasts} onClose={removeToast} />
 */
export function ToastContainer({ toasts = [], onClose }) {
  return (
    <div
      className="fixed bottom-5 right-5 z-[9999] flex flex-col gap-2.5 items-end"
      aria-live="polite"
    >
      {toasts.map((t) => (
        <Toast key={t.id} {...t} onClose={onClose} />
      ))}
    </div>
  );
}